google_adwords.settings:
  type: mapping
  label: Settings
  mapping:
    language:
      type: string
    format:
      type: string
    color:
      type: string
    conversion_id:
      type: string
    external_script:
      type: string