google_adwords_path.google_adwords_path_config.*:
  type: config_entity
  label: 'Google AdWords Path Config config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    enabled:
      type: boolean
      label: 'Enabled'
    conversion_id:
      type: string
      label: 'Conversion ID'
    language:
      type: string
      label: 'Language'
    format:
      type: string
      label: 'Format'
    colour:
      type: string
      label: 'Colour'
    paths:
      type: sequence
      label: 'Paths'
      sequence:
        type: string
        label: 'Path'
